image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
    - build
    - test
    - publish

build:
    stage: build
    script:
        - "dotnet build src/DinoClipper.sln"
    artifacts:
      paths:
        - src/DinoClipper/bin

test:
    stage: test
    script: 
        - "dotnet test src/DinoClipper.sln"

build_docker:
    stage: publish
    image: docker:latest
    services:
        - docker:dind
    before_script:
        - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - tag=$(date +%Y%m%d-%H%M%S)-${CI_COMMIT_SHORT_SHA}
        - docker build --pull -t "${CI_REGISTRY_IMAGE}:latest" -t "${CI_REGISTRY_IMAGE}:${tag}" -f src/DinoClipper/Dockerfile src
        - docker push "${CI_REGISTRY_IMAGE}:latest" "${CI_REGISTRY_IMAGE}:${tag}"
    only:
        - master
