image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - build
    - test

build:
    stage: build
    script:
        - "dotnet build src/DinoClipper.sln"
    artifacts:
      paths:
        - bin/

test:
    stage: test
    script: 
        - "dotnet test src/DinoClipper.sln"
