name: "Release Image"

on:
  push:
    branches: [ "main" ]

jobs:
  build-docker:
    name: "Build & Release Docker Image"
    runs-on: ubuntu-latest
    steps:
      # Setup Environment
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
      # Build Image
      - name: Build
        run: |
          docker build . -f src/DinoClipper/Dockerfile -t ghcr.io/rgunti/dinoclipper:${GITHUB_REF_NAME}
      - name: Push Image (ref name)
        run: |
          docker push ghcr.io/rgunti/dinoclipper:${GITHUB_REF_NAME}
